# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d8915c50c74180f8dd3e425cc53b292e437c2809cdadfb3b0c9f1925fce49c0efc75e4d5b152f8fdd140eacd632c51dd08e3cd11756cb6e0d6a9c011723f09c

test:
  secret_key_base: e58a3a011727c0b9d7175276b11bb592e00340e1f46a3463363c5d8b75d4b312c9aed7404b418b528e4a559b1c5142a01f14440bc414836249d95455109c152b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
